# Generated by Django 5.2.1 on 2025-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=100, verbose_name='Nome')),
                ('crm', models.CharField(help_text='Digite a CRM', max_length=100, unique=True, verbose_name='CRM')),
                ('telefone', models.IntegerField(help_text='Digite o telefone', max_length=11, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Digite o email', max_length=100, unique=True, verbose_name='Email')),
                ('data_nascimento', models.DateField(help_text='Data de Nascimento', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Digite o cpf', max_length=11, unique=True, verbose_name='CPF')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], help_text='Selecione o Status', max_length=100, verbose_name='Status')),
            ],
        ),
    ]
