# Generated by Django 5.2.1 on 2025-05-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(help_text='Digite o RG', max_length=9, unique=True, verbose_name='RG')),
                ('nome_mae', models.CharField(help_text='Nome Completo da Mãe', max_length=100, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, help_text='Nome Completo do Pai (Opcional)', max_length=100, null=True, verbose_name='Nome do Pai (Opcional)')),
                ('telefone_principal', models.CharField(help_text='Digite o Telefone', max_length=11, verbose_name='Telefone')),
                ('telefone_secundario', models.CharField(blank=True, help_text='Digite o Segundo Telefone (Opcional)', max_length=11, null=True, verbose_name='Telefone Secundário')),
                ('email', models.EmailField(help_text='Digite o Email', max_length=100, verbose_name='Email')),
                ('tipo_sanguineo', models.CharField(help_text='Digite o Tipo Sanguíneo', max_length=2, verbose_name='Tipo Sanguíneo')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Setor de Atuação', max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(help_text='Digite o telefone', max_length=11, unique=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=100, verbose_name='Nome')),
                ('coren', models.CharField(help_text='Digite o COREN', max_length=100, verbose_name='Coren')),
                ('tele', models.CharField(help_text='Digite o telefone', max_length=11, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Digite o email', max_length=100, unique=True, verbose_name='Email')),
                ('data_nascimento', models.DateField(help_text='Data de Nascimento', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, unique=True, verbose_name='CPF')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], help_text='Selecione o Status', max_length=100, verbose_name='Status')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prontuario.setor', verbose_name='Setor')),
            ],
        ),
    ]
